name: Build and Release Nuitka Standalone

on:
    push:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write
    pull-requests: write
    issues: write
    actions: read
    checks: write

env:
    PACKAGE_VERSION: 0.4.1

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, ubuntu-latest, macos-latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@main

            - name: Set up Python
              uses: actions/setup-python@main
              with:
                  python-version: "3.12"
                  architecture: "x64"
                  cache: "pip"
                  cache-dependency-path: |
                      **/requirements*.txt

            - name: Install Dependencies
              run: |
                  pip install -r requirements-repo.txt

            - name: Build Executable with Nuitka
              uses: Nuitka/Nuitka-Action@main
              with:
                  nuitka-version: main
                  script-name: phoneme-cmd.py
                  mode: onefile
                  output-dir: phoneme-cli
                  # Add any other Nuitka options you need

            - name: Zip macOS app bundle
              if: matrix.os == 'macos-latest'
              run: |
                  mkdir -p phoneme-cli-mac
                  mv phoneme-cli.app phoneme-cli-mac/phoneme-cli.app
                  cd phoneme-cli-mac
                  zip -r ../phoneme-cli-mac.zip phoneme-cli.app
              shell: bash

            - name: Upload Nuitka build artifact
              uses: actions/upload-artifact@main
              with:
                  name: ${{ runner.os }} Build
                  path: |
                      phoneme-cli/*.exe
                      phoneme-cli/*.bin
                      phoneme-cli.app/**/*
                      phoneme-cli-mac.zip
                  include-hidden-files: true

    release:
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs: build

        steps:
            - name: Checkout code
              uses: actions/checkout@main
              with:
                  fetch-depth: 0

            - name: Download all build artifacts
              uses: actions/download-artifact@main
              with:
                  path: ./phoneme-cli

            - name: Get latest tag
              id: get_tag
              shell: bash
              run: |
                  latest_tag=$(git tag | sort -V | tail -n 1)
                  if [ -z "$latest_tag" ]; then
                    new_tag="v${{ env.PACKAGE_VERSION }}"
                  else
                    random_str=$(openssl rand -hex 4)
                    version_prefix=${{ env.PACKAGE_VERSION }}
                    new_tag="${version_prefix}-${random_str}"
                  fi
                  echo "LATEST_TAG=$new_tag" >> $GITHUB_ENV

            - name: Create tag
              run: |
                  git tag ${{ env.LATEST_TAG }}
                  git push origin ${{ env.LATEST_TAG }}

            - name: Create GitHub release
              id: create_release
              uses: softprops/action-gh-release@c43d7637b9b9ce3e953168c325d27253a5d48d8e
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ env.LATEST_TAG }}
                  name: v${{ env.PACKAGE_VERSION }}
                  body: |
                      Release version ${{ env.PACKAGE_VERSION }} of the project.

            - name: Display the release directory structure
              run: ls -R ./phoneme-cli

            - name: Upload Release Assets
              run: |
                  for file in ./phoneme-cli/**/*; do
                    if [ -f "$file" ]; then
                      gh release upload "${{ env.LATEST_TAG }}" "$file" --clobber
                    fi
                  done
                  if [ -f ./phoneme-cli-mac.zip ]; then
                    gh release upload "${{ env.LATEST_TAG }}" ./phoneme-cli-mac.zip --clobber
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
